# Generated by Django 6.1 on 2026-08-09 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conditions', '0001_initial'),
        ('hotels', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('event_title', models.CharField(max_length=255)),
                ('trip_start_date', models.DateField()),
                ('trip_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exclusions', models.ManyToManyField(blank=True, to='conditions.exclusion')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel')),
                ('inclusions', models.ManyToManyField(blank=True, to='conditions.inclusion')),
                ('places', models.ManyToManyField(blank=True, to='places.place')),
                ('policies', models.ManyToManyField(blank=True, to='conditions.policy')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('meal_plan', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trip_day', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itineraries.itinerary')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryGroupPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_size', models.IntegerField()),
                ('hotel_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('meal_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('travel_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price_per_person', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_group_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_prices', to='itineraries.itinerary')),
            ],
        ),
    ]
