# Generated by Django 6.1 on 2026-08-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_alter_itineraryday_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarygroupprice',
            name='other_charge_type',
            field=models.CharField(blank=True, choices=[('place_charges', 'Place Charges'), ('extra_charges', 'Extra Charges')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='itinerarygroupprice',
            name='travel_type',
            field=models.CharField(blank=True, choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight'), ('taxi', 'Taxi')], max_length=20, null=True),
        ),
    ]
