# Generated by Django 6.1 on 2026-08-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('itineraries', '0003_itinerarygroupprice_other_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_days', to='hotels.hotel'),
        ),
    ]
