# Generated by Django 6.1 on 2026-08-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('itineraries', '0004_itineraryday_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='itineraryday',
            name='hotel',
        ),
        migrations.AddField(
            model_name='itinerarygroupprice',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel'),
        ),
    ]
