# Generated by Django 6.1 on 2026-08-15 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('itineraries', '0005_remove_itinerary_hotel_remove_itineraryday_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='itinerarygroupprice',
            name='meals_included',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
