# Generated by Django 6.1 on 2026-08-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0006_itinerary_hotel_itinerarygroupprice_meals_included'),
        ('places', '0002_city_country_alter_place_city_city_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='places',
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.city'),
        ),
    ]
