# Generated by Django 6.1 on 2026-08-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0007_remove_itinerary_hotel_remove_itinerary_places_and_more'),
        ('places', '0002_city_country_alter_place_city_city_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='places',
            field=models.ManyToManyField(blank=True, to='places.place'),
        ),
    ]
