# Generated by Django 6.1 on 2026-08-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0009_alter_itineraryday_meal_plan_and_more'),
        ('places', '0005_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryitem',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='itinerary_items_multi', to='places.place'),
        ),
    ]
