# Generated by Django 5.0.14 on 2026-08-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0010_itineraryitem_places'),
        ('places', '0005_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='itinerary_days_multi', to='places.place'),
        ),
    ]
