# Generated by Django 5.0.14 on 2026-08-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_importantnote'),
        ('itineraries', '0011_itineraryday_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryday',
            name='places',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='important_notes',
            field=models.ManyToManyField(blank=True, to='conditions.importantnote'),
        ),
    ]
