# Generated by Django 5.0.14 on 2026-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0012_remove_itineraryday_places_itinerary_important_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='status',
            field=models.CharField(default='Confirmed', max_length=50),
        ),
    ]
