# Generated by Django 5.0.14 on 2026-09-05 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0013_itinerary_contact_number_itinerary_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='status',
        ),
    ]
