# Generated by Django 6.1 on 2026-09-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0014_remove_itinerary_contact_number_and_more'),
        ('places', '0005_place_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='itinerary_days_multi', to='places.place'),
        ),
    ]
