# Generated by Django 5.0.14 on 2026-08-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_city_country_alter_place_city_city_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
