# Generated by Django 5.0.14 on 2026-08-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='status',
        ),
    ]
